# Generated by Django 2.1.15 on 2021-02-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210201_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeImage',
            new_name='Image',
        ),
    ]
